const cardInfo = [
    { filename: "blue_0.png", value: 0 },
    { filename: "blue_1.png", value: 1 },
    { filename: "blue_2.png", value: 2 },
    { filename: "blue_3.png", value: 3 },
    { filename: "blue_4.png", value: 4 },
    { filename: "blue_5.png", value: 5 },
    { filename: "blue_6.png", value: 6 },
    { filename: "blue_7.png", value: 7 },
    { filename: "blue_8.png", value: 8 },
    { filename: "blue_9.png", value: 9 },
    { filename: "blue_draw_2.png", value: 20 },
    { filename: "blue_reverse.png", value: 20 },
    { filename: "blue_skip.png", value: 20 },
  
    { filename: "green_0.png", value: 0 },
    { filename: "green_1.png", value: 1 },
    { filename: "green_2.png", value: 2 },
    { filename: "green_3.png", value: 3 },
    { filename: "green_4.png", value: 4 },
    { filename: "green_5.png", value: 5 },
    { filename: "green_6.png", value: 6 },
    { filename: "green_7.png", value: 7 },
    { filename: "green_8.png", value: 8 },
    { filename: "green_9.png", value: 9 },
    { filename: "green_draw_2.png", value: 20 },
    { filename: "green_reverse.png", value: 20 },
    { filename: "green_skip.png", value: 20 },
  
    { filename: "red_0.png", value: 0 },
    { filename: "red_1.png", value: 1 },
    { filename: "red_2.png", value: 2 },
    { filename: "red_3.png", value: 3 },
    { filename: "red_4.png", value: 4 },
    { filename: "red_5.png", value: 5 },
    { filename: "red_6.png", value: 6 },
    { filename: "red_7.png", value: 7 },
    { filename: "red_8.png", value: 8 },
    { filename: "red_9.png", value: 9 },
    { filename: "red_draw_2.png", value: 20 },
    { filename: "red_reverse.png", value: 20 },
    { filename: "red_skip.png", value: 20 },
  
    { filename: "yellow_0.png", value: 0 },
    { filename: "yellow_1.png", value: 1 },
    { filename: "yellow_2.png", value: 2 },
    { filename: "yellow_3.png", value: 3 },
    { filename: "yellow_4.png", value: 4 },
    { filename: "yellow_5.png", value: 5 },
    { filename: "yellow_6.png", value: 6 },
    { filename: "yellow_7.png", value: 7 },
    { filename: "yellow_8.png", value: 8 },
    { filename: "yellow_9.png", value: 9 },
    { filename: "yellow_draw_2.png", value: 20 },
    { filename: "yellow_reverse.png", value: 20 },
    { filename: "yellow_skip.png", value: 20 },

    { filename: "blue_wild.png", value: 50 },
    { filename: "blue_wild_4.png", value: 50 },
  ];

  export default cardInfo;